version: 2

sources:
  - name: tpch
    schema: tpch
    description: Source tables from the TPC-H benchmark dataset at scale factor tiny
    tables:

      - name: customer
        description: Customer master data
        columns:
          - name: custkey
            description: Unique ID of the customer
            tests:
              - not_null
              - unique
          - name: nationkey
            description: Foreign key to nation
            tests:
              - not_null
              - relationships:
                  to: source('tpch', 'nation')
                  field: nationkey

      - name: lineitem
        description: Line items for orders
        columns:
          - name: orderkey
            description: Foreign key to orders
            tests:
              - not_null
              - relationships:
                  to: source('tpch', 'orders')
                  field: orderkey
          - name: partkey
            description: Foreign key to part
            tests:
              - not_null
              - relationships:
                  to: source('tpch', 'part')
                  field: partkey
          - name: suppkey
            description: Foreign key to supplier
            tests:
              - not_null
              - relationships:
                  to: source('tpch', 'supplier')
                  field: suppkey

      - name: nation
        description: Nation reference data
        columns:
          - name: nationkey
            description: Unique nation ID
            tests:
              - not_null
              - unique
          - name: regionkey
            description: Foreign key to region
            tests:
              - not_null
              - relationships:
                  to: source('tpch', 'region')
                  field: regionkey

      - name: orders
        description: Customer orders
        columns:
          - name: orderkey
            description: Unique order ID
            tests:
              - not_null
              - unique
          - name: custkey
            description: Foreign key to customer
            tests:
              - not_null
              - relationships:
                  to: source('tpch', 'customer')
                  field: custkey

      - name: part
        description: Part master data
        columns:
          - name: partkey
            description: Unique part ID
            tests:
              - not_null
              - unique

      - name: partsupp
        description: Part-Supplier bridge table
        columns:
          - name: partkey
            tests:
              - not_null
              - relationships:
                  to: source('tpch', 'part')
                  field: partkey
          - name: suppkey
            tests:
              - not_null
              - relationships:
                  to: source('tpch', 'supplier')
                  field: suppkey

      - name: region
        description: Region reference data
        columns:
          - name: regionkey
            description: Unique region ID
            tests:
              - not_null
              - unique

      - name: supplier
        description: Supplier master data
        columns:
          - name: suppkey
            description: Unique supplier ID
            tests:
              - not_null
              - unique
          - name: nationkey
            description: Foreign key to nation
            tests:
              - not_null
              - relationships:
                  to: source('tpch', 'nation')
                  field: nationkey