dbt_trino_project:
  outputs:

    dev:
      type: trino
      method: none  # optional, one of {none | ldap | kerberos}
      user: tunguyenn99
      password: ''  # required if method is ldap or kerberos
      database: minio
      host: trino-coordinator # <<== Đổi tên host từ localhost sang trino-coordinator do đã mở kết nối mạng docker
      port: 8088
      schema: tpch
      threads: 4

    prod:
      type: trino
      method: none  # optional, one of {none | ldap | kerberos}
      user: tunguyenn99
      password: ''  # required if method is ldap or kerberos
      database: minio
      host: trino-coordinator # <<== Đổi tên host từ localhost sang trino-coordinator do đã mở kết nối mạng docker
      port: 8088
      schema: tpch
      threads: 4

  target: dev