version: 2

models:
  - name: int_order_revenue
    description: Revenue and item count per order
    columns:
      - name: orderkey
        description: Unique identifier for each order
        tests:
          - not_null
          - unique
      - name: item_count
        description: Number of items in the order
        tests:
          - not_null

  - name: int_customer_segment
    description: Aggregated customer orders and revenue by marketing segment
    columns:
      - name: total_orders
        description: Total number of orders in this segment
        tests:
          - not_null

  - name: int_product_profitability
    description: Revenue, cost, and profit per product-supplier pair
    columns:
      - name: partkey
        description: Product identifier
        tests:
          - not_null
          - relationships:
              to: ref('stg_part')
              field: partkey
      - name: suppkey
        description: Supplier identifier
        tests:
          - not_null
          - relationships:
              to: ref('stg_supplier')
              field: suppkey
