version: 2

models:
  - name: mart_sales_by_date
    description: Daily revenue summary
    columns:
      - name: total_revenue
        description: Tổng doanh thu trong ngày
        tests:
          - not_null

  - name: mart_customer_lifetime_value
    description: Customer revenue metrics
    columns:
      - name: custkey
        description: Customer ID
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('stg_customer')
              field: custkey
      - name: total_revenue
        description: Tổng doanh thu của khách hàng

  - name: mart_top_products
    description: Top-selling products
    columns:
      - name: partkey
        description: Product ID
        tests:
          - not_null
          - relationships:
              to: ref('stg_part')
              field: partkey
      - name: total_revenue
        description: Tổng doanh thu của sản phẩm
        tests:
          - not_null
